baseurl: 'https://www.josherich.me'
projecturl: '/projects/'
permalink: /:categories/:title
name: Josherich's Blog
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
data_format: "ordinal"
subscribe_rss: /atom.xml
encoding: utf-8
sass:
    style: compressed
    sass_dir: _sass
gems:
  - jekyll-feed