baseurl: 'http://www.chenhf.com'
projecturl: '/projects/'
permalink: /:categories/:title
name: I blog when I'm bored
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
data_format: "ordinal"
subscribe_rss: /atom.xml
encoding: utf-8
