baseurl: 'https://www.josherich.me'
projecturl: '/projects/'
permalink: /:categories/:title
name: Josherich's Blog
title: "Josherich's Blog"
description: "home sweet home"
url: "https://josherich.me"
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  gfm_quirks: paragraph_end
highlighter: rouge
data_format: "ordinal"
subscribe_rss: /atom.xml
encoding: utf-8
sass:
    style: compressed
    sass_dir: _sass
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji